### ISSUE TITLE
edit-validator: moniker changed to 'your-moniker' despite not specified

### ISSUE THREAD

**Issue by kenorb** [FunctionX/fx-core#17]
I've run the following command without `--moniker`:

```
fxcore@7b36c9e12a46:~$ fxcored tx staking edit-validator --from=test --website="https://example.com" --details="To infinity and beyond!" --security-contact="security@example.com" --gas auto --gas-adjustment=1.2 --gas-prices="6000000000000FX" --yes
gas estimate: 67264
{"height":"2015917","txhash":"9B236B7A56778483BBA126040763AA3D00C61F379454B11C1E565774D6217FF8","codespace":"","code":0,"data":"0A100A0E656469745F76616C696461746F72","raw_log":"[{\"events\":[{\"type\":\"edit_validator\",\"attributes\":[{\"key\":\"commission_rate\",\"value\":\"commissionrates:\\n  rate: \\\"0.005000000000000000\\\"\\n  max_rate: \\\"0.200000000000000000\\\"\\n  max_change_rate: \\\"0.010000000000000000\\\"\\nupdate_time: 2021-10-11T17:24:59.288210099Z\\n\"},{\"key\":\"min_self_delegation\",\"value\":\"1000000000000000000\"}]},{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"edit_validator\"},{\"key\":\"module\",\"value\":\"staking\"},{\"key\":\"sender\",\"value\":\"fxvaloper1testq0nmkkpd84qj4rde7l42a5nw3g8k5fpm77\"}]}]}]","logs":[{"msg_index":0,"log":"","events":[{"type":"edit_validator","attributes":[{"key":"commission_rate","value":"commissionrates:\n  rate: \"0.005000000000000000\"\n  max_rate: \"0.200000000000000000\"\n  max_change_rate: \"0.010000000000000000\"\nupdate_time: 2021-10-11T17:24:59.288210099Z\n"},{"key":"min_self_delegation","value":"1000000000000000000"}]},{"type":"message","attributes":[{"key":"action","value":"edit_validator"},{"key":"module","value":"staking"},{"key":"sender","value":"fxvaloper1testq0nmkkpd84qj4rde7l42a5nw3g8k5fpm77"}]}]}],"info":"","gas_wanted":"67264","gas_used":"66472","tx":null,"timestamp":""}
```

but it changed moniker to `'your-moniker'`.

Transaction: [0x9B236B7A56778483BBA126040763AA3D00C61F379454B11C1E565774D6217FF8](https://aabbcc-explorer.functionx.io/fxcore/tx/0x9B236B7A56778483BBA126040763AA3D00C61F379454B11C1E565774D6217FF8)

These are the values which are not expected:

>  "moniker": "your-moniker"

>  "identity": "[do-not-modify]",

Further issues:

- When changed a security contact, it's shown empty when checking via `fxcored query staking validator`.
- When changed 'details' field, it's still showing then old one when specified on the validator creation. Checked by the above command.
- Explorer website also got problems and not updating some fields, reported this separately at the [forum](https://forum.functionx.io/t/validators-details-website-and-contact-not-updated/2118).

**Comment by zakir-code** [comment]
I found the validator information at block height 2024529 (2021-11-20T08:36:47.224194515Z)

```
ubuntu@ip-172-20-71-245:~$ fxcored query staking validator fxvaloper1testq0nmkkpd84qj4rde7l42a5nw3g8k5fpm77 --height 2024529
commission:
  commission_rates:
    max_change_rate: "0.010000000000000000"
    max_rate: "0.200000000000000000"
    rate: "0.005000000000000000"
  update_time: "2021-10-11T17:24:59.288210099Z"
consensus_pubkey:
  '@type': /cosmos.crypto.ed25519.PubKey
  key: FEZz5DIUlb/wX+otO12y+Y89LAFrCyMTLl+hajBaDx4=
delegator_shares: "1400584238968077351915.735754119592503430"
description:
  details: To infinity and beyond!
  identity: ""
  moniker: Test
  security_contact: security@example.com
  website: https://example.com
jailed: true
min_self_delegation: "1000000000000000000"
operator_address: fxvaloper1testq0nmkkpd84qj4rde7l42a5nw3g8k5fpm77
status: BOND_STATUS_UNBONDING
tokens: "1396600000000000000000"
unbonding_height: "2021043"
unbonding_time: "2021-12-11T03:19:09.601206856Z"
```

We will fix the block explorer as soon as possible
